### ISSUE TITLE
钱包如何转账

### ISSUE THREAD

**Issue by neal-zhu** [Qitmeer/qitmeer-wallet#16]
编译好钱包之后，使用命令：
```
 ./qitmeer-wallet  qc sendtoaddress TmWMuY9q5dUutUTGikhqTVKrnDMG34dEgb5 1 mypassword
```
报错：
```
2020-01-02|22:29:53.947 [TRACE] OpenExistingWallet                  dbPath=/home/ray/.qitwallet/testnet/wallet.db
2020-01-02|22:29:53.947 [TRACE] OpenExistingWallet                  open db=succ
2020-01-02|22:29:53.947 [TRACE] OpenExistingWallet                  ooooopen=1
2020-01-02|22:29:55.000 [TRACE] OpenExistingWallet                  open error="invalid passphrase for master public key"
openWallet err:invalid passphrase for master public key
```
config.toml :
```toml
DebugLevel = "trace"
Create = false
Network = "testnet"
UI = true
Listeners = ["127.0.0.1:38130"]
RPCUser = "admin"
RPCPass = "123456"
RPCMaxClients = 10
DisableRPC = false
DisableTLS = true
MinTxFee = 200000
APIs = ["account", "wallet", "qitmeerd"]
QServer = ""
QUser = ""
QPass = ""
QCert = ""
QNoTLS = true
QTLSSkipVerify = true
QProxy = ""
QProxyUser = ""
QProxyPass = ""
WalletPass = "123456"
QitmeerdSelect = "local"

[[Qitmeerds]]
  Name = "node10"
  RPCUser = "qitmeer"
  RPCPassword = "123456"
  RPCServer = "127.0.0.1:18130"
  RPCCert = ""
  NoTLS = true
  TLSSkipVerify = true
  Proxy = ""
  ProxyUser = ""
  ProxyPass = ""
```
